/**
 * A bare-bones simplifier for shortening the scramble and generating a solution
 * @param {Array<RotationNotation>} scramble 
 * @returns {{
 *  scramble: Array<RotationNotation>, 
 *  solution: Array<RotationNotation>, 
 *  changed: bool
 * }}
 */
export default function solveAndSimplify(scramble) {
    let newScramble = [...scramble]
    let changed = true // set to true to run loop at least once
    let passCounter = 0 // the number of passes done (if more than one then changes were made)

    // pass over multiple times to check for cascading rules
    while (changed) {
        ({newScramble, changed} = singlePass(newScramble))
        passCounter += 1;
    }

    const solution = invert(newScramble)

    return {
        scramble: newScramble,
        solution: solution,
        changed: passCounter > 1
    }
}

/**
 * generates a solution for the given scramble
 * reverses the array and inverts every move
 * @param {Array<RotationNotation>} rotationData 
 * @returns {Array<RotationNotation>}
 */
function invert(rotationData) {
    return rotationData.toReversed().map((data) => data.fliped())
}

/**
 * does a single pass over the array looking for rule hits
 * simplifies the array if any hits
 * @param {Array<RotationNotation>} scramble 
 * @returns {{
 *  newScramble: Array<RotationNotation>,
 *  changed: bool
 * }}
 */
function singlePass(scramble) {
    const newScramble = []
    let changed = false
    let failed = [] // a list of failed checks incase of lookover checks passing

    let comp = 0 // the index of the scramble thats being compared against
    let current = 1 // the index of the scramble thats being compared to

    // iterate through all valid pairs (-1 for the pair (end-1, end))
    while (comp < scramble.length-1) {
        // check for a simplification on the pair
        const {hit, replace} = simplify(scramble[comp], scramble[current])
        
        // if a rule is identified for the pair
        if (hit) {
            // if it has a replacement move push that to the new scramble
            if (replace) {                
                newScramble.push(replace)
            }
            newScramble.push(...failed) // push all the skipped currents after as well
            failed = []                 // reset the failed array
            changed = true              // set the changed flag
            comp = current+1            // set comp to pass over all values that have been compared
            current = comp+1            // set current to be the one after comp
        } else if ( // if current is not at the end of the list and current and the next in line are on the same axis
            current < scramble.length-1 &&
            scramble[current].axis === scramble[current+1].axis
        ) { 
            // a check for the one after is allowed since they are independent
            failed.push(scramble[current])  // push the current to the failed list
            current += 1                    // increment current
        } else {
            // if there are no more possible comparisons left for comp
            newScramble.push(scramble[comp])    // push comp
            failed = []                         // reset failed array
            comp += 1                           // increment comp
            current = comp+1                    // set current to the one after comp
        }
    }

    // if no rule was found for the last value
    if (comp === scramble.length-1) {
        newScramble.push(scramble[comp]) // push the last value
    }

    return {
        newScramble: newScramble,
        changed: changed
    }
}


/**
 * checks over each rule for a hit on the given inputs
 * if any rule hits returns the replacement for the input (if null replace with nothing)
 * @param {RotationNotation} comp 
 * @param {RotationNotation} current 
 * @returns {{
 *  hit: bool
 *  replace: RotationNotation
 * }}
 */
function simplify(comp, current) {
    const rules = [
        simplifyReverse,
        simplifyDouble,
        simplifyDoubleSingle
    ]

    // check all rules for possible simplification
    for (const rule of rules) {
        const {hit, replace} = rule(comp, current)
        
        if (hit) {
            // if one hits return the object generated by it
            return {
                hit: hit,
                replace: replace
            }
        }
    }
    // if none hit return object with hit = false
    return {
        hit: false,
        replace: null
    }
}

/*------------------------------------------------------
    All of the simplification rules are defined below   
------------------------------------------------------*/

function simplifyReverse(comp, current) {
    const replace = null
    if (
        comp.inset === current.inset &&
        comp.side === current.side &&
        comp.fliped().rotation === current.rotation
    ) {
        return  {
            hit: true,
            replace: replace
        }
    }
    return {
        hit: false,
        replace: null
    }
}

function simplifyDouble(comp, current) {
    const replaceA = null
    const replaceB = comp.clone().setRotation("2")
    if (
        comp.inset === current.inset &&
        comp.side === current.side &&
        comp.rotation === current.rotation
    ) {
        if (current.rotation === '2') {
            return  {
                hit: true,
                replace: replaceA
            }
        } else {
           return  {
                hit: true,
                replace: replaceB
            } 
        }
    }
    return {
        hit: false,
        replace: null
    }
}

function simplifyDoubleSingle(comp, current) {
    const replaceA = comp.clone().setRotation("")
    const replaceB = comp.clone().setRotation("'")
    if (
        comp.inset === current.inset &&
        comp.side === current.side
    ) {
        if(
            (comp.rotation === "2" && current.rotation === "'") ||
            (comp.rotation === "'" && current.rotation === "2")
        ) {
            return {
                hit: true,
                replace: replaceA
            }
        } else if (
            (comp.rotation === "2" && current.rotation === "") ||
            (comp.rotation === "" && current.rotation === "2")
        ) {
            return {
                hit: true,
                replace: replaceB
            }
        }
    }
    return {
        hit: false,
        replace: null
    }
}