export default function solveAndSimplify(scramble) {
    const newScramble = []
    let changed = false
    let failed = []

    let comp = 0
    let current = 1
    // pass over each current value
    while (comp < scramble.length-1) {
        // check if the next one follows a simplification rule        
        const {hit, replace} = simplify(scramble[comp], scramble[current])
        
        if (hit) {                
            // if a rule hits follow the replacement rules it has and run again 
            if (replace) {                
                newScramble.push(replace)
            }
            newScramble.push(...failed)
            failed = []
            changed = true
            comp = current+1
            current = comp+1
        } else if (
            current < scramble.length-1 &&
            scramble[current].axis === scramble[current+1].axis
        ) { 
            // if no rules pass check if the one after is order independent
            failed.push(scramble[current])
            current += 1
        } else {
            // repeat until no rotation independent values are left
            newScramble.push(scramble[comp], ...failed)
            failed = []
            comp += 1
            current = comp+1
        }
    }

    if (comp === scramble.length-1) {
        newScramble.push(scramble[comp])
    }

    const solution = invert(newScramble)

    return {
        scramble: newScramble,
        solution: solution,
        changed: changed
    }
}

function invert(rotationData) {
    return rotationData.toReversed().map((data) => data.fliped())
}

function simplify(comp, current) {
    const rules = [
        simplifyReverse,
        simplifyDouble,
        simplifyToDouble,
        simplifyReverseFromDouble
    ]

    // check all rules for possible simplification
    for (const rule of rules) {
        const {hit, replace} = rule(comp, current)
        
        if (hit) {
            // if one hits return the object generated by it
            return {
                hit: hit,
                replace: replace
            }
        }
    }
    // if none hit return object with hit = false
    return {
        hit: false,
        replace: null
    }
}

function simplifyReverse(comp, current) {
    const replace = null
    if (
        comp.inset === current.inset &&
        comp.side === current.side &&
        comp.fliped().rotation === current.rotation
    ) {
        return  {
            hit: true,
            replace: replace
        }
    }
    return {
        hit: false,
        replace: null
    }
}

function simplifyDouble(comp, current) {
    const replace = comp.clone().setRotation("2")
    if (
        comp.inset === current.inset &&
        comp.side === current.side &&
        comp.rotation === current.rotation &&
        current.rotation === '2'
    ) {
        return  {
            hit: true,
            replace: replace
        }
    }
    return {
        hit: false,
        replace: null
    }
}

function simplifyToDouble(comp, current) {
    const replace = comp.clone().setRotation("2")
    if (
        comp.inset === current.inset &&
        comp.side === current.side &&
        comp.rotation === current.rotation &&
        current.rotation != "2"
    ) {
        return  {
            hit: true,
            replace: replace
        }
    }
    return {
        hit: false,
        replace: null
    }
}

function simplifyReverseFromDouble(comp, current) {
    const replaceA = comp.clone().setRotation("")
    const replaceB = comp.clone().setRotation("'")
    if (
        comp.inset === current.inset &&
        comp.side === current.side
    ) {
        if(
            (comp.rotation === "2" && current.rotation === "'") ||
            (comp.rotation === "'" && current.rotation === "2")
        ) {
            return {
                hit: true,
                replace: replaceA
            }
        } else if (
            (comp.rotation === "2" && current.rotation === "") ||
            (comp.rotation === "" && current.rotation === "2")
        ) {
            return {
                hit: true,
                replace: replaceB
            }
        }
    }
    return {
        hit: false,
        replace: null
    }
}