export default function solveAndSimplify(scramble) {
    let newScramble = [...scramble]
    let repass = true
    let passCounter = 0

    while (repass) {
        passCounter += 1;
        ({newScramble, repass} = singlePass(newScramble))
    }

    const solution = invert(newScramble)

    return {
        scramble: newScramble,
        solution: solution,
        changed: passCounter > 1
    }
}

function singlePass(scramble) {
    const newScramble = []
    let changed = false
    let failed = []

    let comp = 0
    let current = 1

    // iterate through all valid pairs (-1 for the pair (end-1, end))
    while (comp < scramble.length-1) {
        // check for a simplification on the pair
        const {hit, replace} = simplify(scramble[comp], scramble[current])
        
        // if a rule is identified for the pair
        if (hit) {
            // if it has a replacement move push that to the new scramble
            if (replace) {                
                newScramble.push(replace)
            }
            newScramble.push(...failed) // push all the skipped currents after as well
            failed = []                 // reset the failed array
            changed = true              // set the changed flag
            comp = current+1            // set comp to pass over all values that have been compared
            current = comp+1            // set current to be the one after comp
        } else if ( // if current is not at the end of the list and current and the next in line are on the same axis
            current < scramble.length-1 &&
            scramble[current].axis === scramble[current+1].axis
        ) { 
            // a check for the one after is allowed since they are independent
            failed.push(scramble[current])  // push the current to the failed list
            current += 1                    // increment current
        } else {
            // if there are no more possible comparisons left for comp
            newScramble.push(scramble[comp])    // push comp
            failed = []                         // reset failed array
            comp += 1                           // increment comp
            current = comp+1                    // set current to the one after comp
        }
    }

    // if no rule was found for the last value
    if (comp === scramble.length-1) {
        newScramble.push(scramble[comp]) // push the last value
    }

    return {
        newScramble: newScramble,
        changed: changed
    }
}

function invert(rotationData) {
    return rotationData.toReversed().map((data) => data.fliped())
}

function simplify(comp, current) {
    const rules = [
        simplifyReverse,
        simplifyDouble,
        simplifyToDouble,
        simplifyReverseFromDouble
    ]

    // check all rules for possible simplification
    for (const rule of rules) {
        const {hit, replace} = rule(comp, current)
        
        if (hit) {
            // if one hits return the object generated by it
            return {
                hit: hit,
                replace: replace
            }
        }
    }
    // if none hit return object with hit = false
    return {
        hit: false,
        replace: null
    }
}

function simplifyReverse(comp, current) {
    const replace = null
    if (
        comp.inset === current.inset &&
        comp.side === current.side &&
        comp.fliped().rotation === current.rotation
    ) {
        return  {
            hit: true,
            replace: replace
        }
    }
    return {
        hit: false,
        replace: null
    }
}

function simplifyDouble(comp, current) {
    const replace = comp.clone().setRotation("2")
    if (
        comp.inset === current.inset &&
        comp.side === current.side &&
        comp.rotation === current.rotation &&
        current.rotation === '2'
    ) {
        return  {
            hit: true,
            replace: replace
        }
    }
    return {
        hit: false,
        replace: null
    }
}

function simplifyToDouble(comp, current) {
    const replace = comp.clone().setRotation("2")
    if (
        comp.inset === current.inset &&
        comp.side === current.side &&
        comp.rotation === current.rotation &&
        current.rotation != "2"
    ) {
        return  {
            hit: true,
            replace: replace
        }
    }
    return {
        hit: false,
        replace: null
    }
}

function simplifyReverseFromDouble(comp, current) {
    const replaceA = comp.clone().setRotation("")
    const replaceB = comp.clone().setRotation("'")
    if (
        comp.inset === current.inset &&
        comp.side === current.side
    ) {
        if(
            (comp.rotation === "2" && current.rotation === "'") ||
            (comp.rotation === "'" && current.rotation === "2")
        ) {
            return {
                hit: true,
                replace: replaceA
            }
        } else if (
            (comp.rotation === "2" && current.rotation === "") ||
            (comp.rotation === "" && current.rotation === "2")
        ) {
            return {
                hit: true,
                replace: replaceB
            }
        }
    }
    return {
        hit: false,
        replace: null
    }
}